export {
  fetchAlerts,
  fetchCurrentWeek,
  fetchHealth,
  fetchLineup,
  fetchNewsFeed,
  fetchPlayer,
  fetchPlayerBadges,
  fetchPlayerNews,
  fetchPlayerSentiment,
  fetchPredictions,
  fetchProjections,
  fetchSentimentSummary,
  fetchTeamDefenseMetrics,
  fetchTeamEvents,
  fetchTeamRoster,
  fetchTeamSentiment,
  fetchTopProjections,
  searchPlayers,
  // Draft
  fetchDraftBoard,
  draftPick,
  fetchDraftRecommendations,
  startMockDraft,
  advanceMockDraft,
  fetchAdp,
  // Multi-source rankings
  fetchMultiCompareRankings,
  // Game archive
  fetchGames,
  fetchGameSeasons,
} from '@/lib/nfl/api';
