export const TEAM_FULL_NAMES: Record<string, string> = {
  ARI: 'Arizona Cardinals',
  ATL: 'Atlanta Falcons',
  BAL: 'Baltimore Ravens',
  BUF: 'Buffalo Bills',
  CAR: 'Carolina Panthers',
  CHI: 'Chicago Bears',
  CIN: 'Cincinnati Bengals',
  CLE: 'Cleveland Browns',
  DAL: 'Dallas Cowboys',
  DEN: 'Denver Broncos',
  DET: 'Detroit Lions',
  GB: 'Green Bay Packers',
  HOU: 'Houston Texans',
  IND: 'Indianapolis Colts',
  JAX: 'Jacksonville Jaguars',
  KC: 'Kansas City Chiefs',
  LA: 'Los Angeles Rams',
  LAR: 'Los Angeles Rams',
  LAC: 'Los Angeles Chargers',
  LV: 'Las Vegas Raiders',
  OAK: 'Las Vegas Raiders',
  MIA: 'Miami Dolphins',
  MIN: 'Minnesota Vikings',
  NE: 'New England Patriots',
  NO: 'New Orleans Saints',
  NYG: 'New York Giants',
  NYJ: 'New York Jets',
  PHI: 'Philadelphia Eagles',
  PIT: 'Pittsburgh Steelers',
  SEA: 'Seattle Seahawks',
  SF: 'San Francisco 49ers',
  TB: 'Tampa Bay Buccaneers',
  TEN: 'Tennessee Titans',
  WAS: 'Washington Commanders',
};

export const TEAM_SECONDARY_COLORS: Record<string, string> = {
  ARI: '#000000',
  ATL: '#000000',
  BAL: '#000000',
  BUF: '#C60C30',
  CAR: '#101820',
  CHI: '#C83803',
  CIN: '#000000',
  CLE: '#FF3C00',
  DAL: '#869397',
  DEN: '#002244',
  DET: '#B0B7BC',
  GB: '#FFB612',
  HOU: '#A71930',
  IND: '#A2AAAD',
  JAX: '#D7A22A',
  KC: '#FFB81C',
  LA: '#FFA300',
  LAR: '#FFA300',
  LAC: '#FFC20E',
  LV: '#A5ACAF',
  OAK: '#A5ACAF',
  MIA: '#FC4C02',
  MIN: '#FFC62F',
  NE: '#C60C30',
  NO: '#101820',
  NYG: '#A71930',
  NYJ: '#000000',
  PHI: '#A5ACAF',
  PIT: '#101820',
  SEA: '#69BE28',
  SF: '#B3995D',
  TB: '#FF7900',
  TEN: '#4B92DB',
  WAS: '#FFB612',
};

export function getTeamFullName(team: string | null | undefined): string {
  if (!team) return '';
  const key = team.toUpperCase();
  return TEAM_FULL_NAMES[key] ?? team;
}
