-- =============================================================================
-- Migration 001: Sentiment Pipeline Schema
-- =============================================================================
-- Creates the `sentiment` schema and all tables required by the unstructured
-- data pipeline (see .planning/unstructured-data/ARCHITECTURE.md).
--
-- Prerequisites:
--   - PostgreSQL 13+ (Supabase compatible)
--   - pgvector extension (available on all Supabase tiers via Dashboard → Extensions)
--
-- Run order: This migration must run before any Silver processing scripts.
-- =============================================================================

-- Enable pgvector for semantic search on document embeddings.
-- Supabase: enable via Dashboard → Database → Extensions → vector.
CREATE EXTENSION IF NOT EXISTS vector;

-- Isolate all sentiment tables from the existing public schema.
CREATE SCHEMA IF NOT EXISTS sentiment;

-- =============================================================================
-- Table: sentiment.raw_docs
-- =============================================================================
-- Bronze-layer index. Every ingested document gets one row here. The full raw
-- payload (JSON) lives in S3; this table holds just the metadata needed for
-- deduplication, routing to the processing queue, and audit trails.
--
-- source enum values:
--   twitter, rss_espn, rss_nfl, rss_rotoworld, rss_pfft, rss_fantasypros,
--   reddit, nfl_injury_report, nfl_inactives, sleeper
--
-- processing_status enum values:
--   pending, processing, done, failed, skipped
-- =============================================================================
CREATE TABLE IF NOT EXISTS sentiment.raw_docs (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source              VARCHAR(30)     NOT NULL,
    external_id         VARCHAR(255),
    url                 TEXT,
    title               TEXT,
    body_text           TEXT            NOT NULL,
    author              VARCHAR(200),
    published_at        TIMESTAMPTZ     NOT NULL,
    ingested_at         TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    season              SMALLINT        NOT NULL,
    week                SMALLINT,                       -- NULL for off-season content
    s3_key              TEXT,                           -- Full key in nfl-raw bucket
    processing_status   VARCHAR(20)     NOT NULL DEFAULT 'pending',
    processing_attempts SMALLINT        DEFAULT 0,
    error_message       TEXT,
    UNIQUE(source, external_id)
);

CREATE INDEX IF NOT EXISTS idx_raw_docs_status
    ON sentiment.raw_docs(processing_status);
CREATE INDEX IF NOT EXISTS idx_raw_docs_published
    ON sentiment.raw_docs(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_raw_docs_season_week
    ON sentiment.raw_docs(season, week);

-- =============================================================================
-- Table: sentiment.doc_signals
-- =============================================================================
-- Silver-layer output. One row per document per mentioned player. A single
-- article mentioning three players produces three rows — one per player.
-- All rows here are generated by Claude (except official injury reports, which
-- map directly to structured fields without LLM processing).
--
-- category enum values:
--   injury, usage, trade, weather, lineup, scheme, practice, contract, general
--
-- model_version: Claude model used for extraction, e.g. "claude-haiku-4-5"
-- =============================================================================
CREATE TABLE IF NOT EXISTS sentiment.doc_signals (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    raw_doc_id              UUID            NOT NULL
                                REFERENCES sentiment.raw_docs(id) ON DELETE CASCADE,
    player_id               VARCHAR(20)     NOT NULL,   -- nfl-data-py gsis_id format
    player_name             VARCHAR(100)    NOT NULL,
    team                    VARCHAR(5),
    season                  SMALLINT        NOT NULL,
    week                    SMALLINT,

    -- Sentiment scores
    sentiment_score         DECIMAL(4,3)    NOT NULL,   -- -1.000 to +1.000
    sentiment_confidence    DECIMAL(4,3)    NOT NULL,   -- 0.000 to 1.000

    -- Categorization
    category                VARCHAR(20)     NOT NULL,
    subcategory             VARCHAR(40),

    -- Event flags — binary signals consumed directly by projection_engine.py
    is_ruled_out            BOOLEAN         DEFAULT FALSE,
    is_limited_practice     BOOLEAN         DEFAULT FALSE,
    is_full_practice        BOOLEAN         DEFAULT FALSE,
    is_depth_chart_rise     BOOLEAN         DEFAULT FALSE,
    is_depth_chart_drop     BOOLEAN         DEFAULT FALSE,
    is_inactive             BOOLEAN         DEFAULT FALSE,  -- official NFL inactive list only
    is_questionable         BOOLEAN         DEFAULT FALSE,
    is_doubtful             BOOLEAN         DEFAULT FALSE,

    -- Provenance
    extracted_at            TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    model_version           VARCHAR(30)     NOT NULL,
    raw_excerpt             TEXT,           -- Sentence(s) that drove the extraction

    UNIQUE(raw_doc_id, player_id)
);

CREATE INDEX IF NOT EXISTS idx_doc_signals_player
    ON sentiment.doc_signals(player_id, season, week);
CREATE INDEX IF NOT EXISTS idx_doc_signals_category
    ON sentiment.doc_signals(category, season, week);
-- Partial index: fast look-up of ruled-out players for game-day processing
CREATE INDEX IF NOT EXISTS idx_doc_signals_ruled_out
    ON sentiment.doc_signals(is_ruled_out, season, week)
    WHERE is_ruled_out = TRUE;

-- =============================================================================
-- Table: sentiment.doc_embeddings
-- =============================================================================
-- Stores vector embeddings for semantic search (e.g. "find all articles
-- similar to this injury update"). Requires pgvector.
-- Dimension 1536 matches OpenAI text-embedding-3-small.
-- The HNSW index enables sub-millisecond approximate nearest-neighbor search.
-- =============================================================================
CREATE TABLE IF NOT EXISTS sentiment.doc_embeddings (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    raw_doc_id  UUID        NOT NULL REFERENCES sentiment.raw_docs(id) ON DELETE CASCADE,
    player_id   VARCHAR(20) NOT NULL,
    embedding   vector(1536),
    model       VARCHAR(50) NOT NULL,       -- e.g. "text-embedding-3-small"
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(raw_doc_id, player_id)
);

-- HNSW index for approximate nearest-neighbor search (cosine distance)
CREATE INDEX IF NOT EXISTS idx_embeddings_vector
    ON sentiment.doc_embeddings
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- =============================================================================
-- Table: sentiment.player_week_signals
-- =============================================================================
-- Gold-layer aggregation. One row per player per week. This is the ONLY table
-- that projection_engine.py reads. The sentiment_multiplier here is applied
-- multiplicatively on top of the existing injury and Vegas multipliers.
--
-- sentiment_multiplier range: 0.70 (severe negative news) to 1.15 (very
-- positive news). Neutral default = 1.0000.
--
-- Source breakdown columns count contributing documents by origin.
-- =============================================================================
CREATE TABLE IF NOT EXISTS sentiment.player_week_signals (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    player_id               VARCHAR(20)     NOT NULL,
    player_name             VARCHAR(100)    NOT NULL,
    team                    VARCHAR(5)      NOT NULL,
    season                  SMALLINT        NOT NULL,
    week                    SMALLINT        NOT NULL,

    -- Aggregated sentiment
    sentiment_multiplier    DECIMAL(5,4)    NOT NULL DEFAULT 1.0000,
    sentiment_score_avg     DECIMAL(4,3),
    sentiment_score_max     DECIMAL(4,3),
    sentiment_score_min     DECIMAL(4,3),
    doc_count               SMALLINT        DEFAULT 0,

    -- Event flags — OR of all contributing doc_signals rows
    is_ruled_out            BOOLEAN         DEFAULT FALSE,
    is_inactive             BOOLEAN         DEFAULT FALSE,
    is_questionable         BOOLEAN         DEFAULT FALSE,
    is_doubtful             BOOLEAN         DEFAULT FALSE,
    is_limited_practice     BOOLEAN         DEFAULT FALSE,
    is_full_practice        BOOLEAN         DEFAULT FALSE,
    is_depth_chart_rise     BOOLEAN         DEFAULT FALSE,
    is_depth_chart_drop     BOOLEAN         DEFAULT FALSE,

    -- Source breakdown
    twitter_doc_count       SMALLINT        DEFAULT 0,
    rss_doc_count           SMALLINT        DEFAULT 0,
    official_report_count   SMALLINT        DEFAULT 0,
    reddit_doc_count        SMALLINT        DEFAULT 0,
    sleeper_doc_count       SMALLINT        DEFAULT 0,

    -- Freshness metadata
    latest_signal_at        TIMESTAMPTZ,
    computed_at             TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    signal_staleness_hours  DECIMAL(5,1),

    UNIQUE(player_id, season, week)
);

CREATE INDEX IF NOT EXISTS idx_player_week_signals_lookup
    ON sentiment.player_week_signals(player_id, season, week);
CREATE INDEX IF NOT EXISTS idx_player_week_signals_flags
    ON sentiment.player_week_signals(season, week, is_ruled_out, is_inactive);

-- =============================================================================
-- Table: sentiment.ingestion_runs
-- =============================================================================
-- Audit log for all ingestion jobs. Used for monitoring, deduplication windows,
-- and debugging. The metadata JSONB column holds source-specific state (e.g.
-- last tweet ID for cursor-based pagination on Twitter).
--
-- run_type enum values: batch, realtime, backfill
-- =============================================================================
CREATE TABLE IF NOT EXISTS sentiment.ingestion_runs (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source          VARCHAR(30)     NOT NULL,
    run_type        VARCHAR(20)     NOT NULL,
    started_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    completed_at    TIMESTAMPTZ,
    docs_fetched    INT             DEFAULT 0,
    docs_new        INT             DEFAULT 0,
    docs_duplicate  INT             DEFAULT 0,
    docs_failed     INT             DEFAULT 0,
    error_message   TEXT,
    metadata        JSONB           -- Source-specific cursor / pagination state
);
